FROM golang:1.20 AS builder
RUN mkdir /app
ADD . /app
WORKDIR /app
RUN CGO_ENABLED=0 GOOS=linux go build -gcflags "all=-N -l" -o app cmd/server/main.go
RUN CGO_ENABLED=0 GOOS=linux go install -ldflags "-s -w -extldflags '-static'" github.com/go-delve/delve/cmd/dlv@latest

FROM alpine:latest AS production
COPY --from=builder /app .
COPY --from=builder /go/bin/dlv .
CMD [ "./dlv", "--listen=:4040", "--continue", "--accept-multiclient", "--headless=true", "--api-version=2", "exec", "./app" ]