version: "3"

tasks:
  build:
    cmds:
      - go build -o app cmd/server/main.go
  test:
    cmds:
      - go test -v ./...
  lint:
    cmds:
      - golangci-lint run
  run:
    cmds:
      - docker-compose up --build
  run-debug:
    cmds:
      - docker-compose -f docker-compose.dev.yml up --build
  integration-test:
    cmds:
      - docker-compose up -d db
      - go test -tags=integration -v ./...
    env:
      DB_HOST: localhost
      DB_PORT: 5432
      DB_DB: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_TABLE: postgres
      SSL_MODE: disable
  acceptance-test:
    cmds:
      - docker-compose up -d --build
      - go test -tags=e2e -v ./...
  proto:
    cmds:
      - protoc api/v1/*.proto --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative